---create user table

CREATE TABLE [User]
(
	UserId INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(60) NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	PassWord VARCHAR(10) NOT NULL

);
--CREATE CUSTOMER TABLE

CREATE TABLE[Customer]
(
   CustomerId INT PRIMARY KEY IDENTITY,
   FullName VARCHAR(100) NOT NULL,
   DocumentNumber VARCHAR(10) NOT NULL
)

---CREATE BOOKING 

CREATE TABLE[Booking]
(
	  BookingId INT PRIMARY KEY IDENTITY,
	  RegisterDate DATETIME NOT NULL,
	  Code VARCHAR(50) NOT NULL,
	  Type VARCHAR(50) NOT NULL,
	  UserId INT NOT NULL,  
	  CustomerId INT NOT NULL,
	  FOREIGN KEY (UserId) REFERENCES [User](UserId),
	  FOREIGN KEY (CustomerId) REFERENCES [Customer](CustomerId),
)